{- HLINT ignore -}
{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# OPTIONS_GHC -Wno-unused-imports -Wno-unused-matches -Wno-unused-top-binds #-}
-- | Auto-generated protobuf types from package @opentelemetry.proto.collector.logs.v1@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.OpenTelemetry.Proto.Collector.Logs.V1.LogsService where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Wireform.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.Internal.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe, protoBytesToJSON)
import Data.Proxy (Proxy(..))
import Data.Reflection (Given(..), given)
import Proto.Internal.JSON.Extension qualified as PJExt
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import Proto.Registry (IsMessage)
import Proto.Registry qualified
import qualified Proto.Extension
import Proto.Internal.Wire (Tag(..), WireType(..))
import Proto.Internal.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Internal.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage,
  archVarintSize, archStringSize, archBytesSize, archBoolSize,
  archFixed32Size, archFixed64Size, archSubmessageSize)
import qualified Proto.OpenTelemetry.Proto.Logs.V1.Logs as OT_Proto_Logs_V1_Logs

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x38\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2f\x70\x72\x6f\x74\x6f\x2f\x63\x6f\x6c\x6c\x65\x63\x74\x6f\x72\x2f\x6c\x6f\x67\x73\x2f\x76\x31\x2f\x6c\x6f\x67\x73\x5f\x73\x65\x72\x76\x69\x63\x65\x2e\x70\x72\x6f\x74\x6f\x12\x25\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2e\x70\x72\x6f\x74\x6f\x2e\x63\x6f\x6c\x6c\x65\x63\x74\x6f\x72\x2e\x6c\x6f\x67\x73\x2e\x76\x31\x1a\x26\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2f\x70\x72\x6f\x74\x6f\x2f\x6c\x6f\x67\x73\x2f\x76\x31\x2f\x6c\x6f\x67\x73\x2e\x70\x72\x6f\x74\x6f\x22\x5b\x0a\x18\x45\x78\x70\x6f\x72\x74\x4c\x6f\x67\x73\x53\x65\x72\x76\x69\x63\x65\x52\x65\x71\x75\x65\x73\x74\x12\x3f\x0a\x0d\x72\x65\x73\x6f\x75\x72\x63\x65\x5f\x6c\x6f\x67\x73\x18\x01\x20\x03\x28\x0b\x32\x28\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2e\x70\x72\x6f\x74\x6f\x2e\x6c\x6f\x67\x73\x2e\x76\x31\x2e\x52\x65\x73\x6f\x75\x72\x63\x65\x4c\x6f\x67\x73\x22\x4e\x0a\x19\x45\x78\x70\x6f\x72\x74\x4c\x6f\x67\x73\x53\x65\x72\x76\x69\x63\x65\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x31\x0a\x0f\x70\x61\x72\x74\x69\x61\x6c\x5f\x73\x75\x63\x63\x65\x73\x73\x18\x01\x20\x01\x28\x0b\x32\x18\x45\x78\x70\x6f\x72\x74\x4c\x6f\x67\x73\x50\x61\x72\x74\x69\x61\x6c\x53\x75\x63\x63\x65\x73\x73\x22\x4f\x0a\x18\x45\x78\x70\x6f\x72\x74\x4c\x6f\x67\x73\x50\x61\x72\x74\x69\x61\x6c\x53\x75\x63\x63\x65\x73\x73\x12\x1c\x0a\x14\x72\x65\x6a\x65\x63\x74\x65\x64\x5f\x6c\x6f\x67\x5f\x72\x65\x63\x6f\x72\x64\x73\x18\x01\x20\x01\x28\x03\x12\x15\x0a\x0d\x65\x72\x72\x6f\x72\x5f\x6d\x65\x73\x73\x61\x67\x65\x18\x02\x20\x01\x28\x09\x32\x4c\x0a\x0b\x4c\x6f\x67\x73\x53\x65\x72\x76\x69\x63\x65\x12\x3d\x0a\x06\x45\x78\x70\x6f\x72\x74\x12\x18\x45\x78\x70\x6f\x72\x74\x4c\x6f\x67\x73\x53\x65\x72\x76\x69\x63\x65\x52\x65\x71\x75\x65\x73\x74\x1a\x19\x45\x78\x70\x6f\x72\x74\x4c\x6f\x67\x73\x53\x65\x72\x76\x69\x63\x65\x52\x65\x73\x70\x6f\x6e\x73\x65\x62\x06\x70\x72\x6f\x74\x6f\x33"


-- | Service that can be used to push logs between one Application instrumented with
-- OpenTelemetry and an collector, or between an collector and a central collector (in this
-- case logs are sent/received to/from multiple Applications).
--
-- gRPC service @opentelemetry.proto.collector.logs.v1.LogsService@.
--
-- Methods:
-- * Export (ExportLogsServiceRequest -> ExportLogsServiceResponse)
-- | Server handler record for @LogsService@.
-- Each field is a handler function for one RPC method.
-- Implement all fields to create a server.
data LogsServiceServer m = LogsServiceServer
  { exportHandler :: ExportLogsServiceRequest -> m ExportLogsServiceResponse
  }

-- | Client stub record for @LogsService@.
-- Each field is a function for calling one RPC method.
data LogsServiceClient m = LogsServiceClient
  { export :: ExportLogsServiceRequest -> m ExportLogsServiceResponse
  }

-- | Method metadata for @LogsService@.
data LogsServiceMethod
  = ExportMethod
  deriving stock (Show, Eq, Ord, Enum, Bounded)

logsserviceMethodName :: LogsServiceMethod -> Text
logsserviceMethodName ExportMethod = "Export"

-- | Fully-qualified service name: @LogsService@
logsserviceServiceName :: Text
logsserviceServiceName = "LogsService"

-- | All method paths for @LogsService@.
logsserviceMethodPaths :: [Text]
logsserviceMethodPaths = ["/LogsService/Export"]

data ExportLogsServiceRequest = ExportLogsServiceRequest
  { exportLogsServiceRequestResourceLogs :: !(V.Vector OT_Proto_Logs_V1_Logs.ResourceLogs)
    -- ^ An array of ResourceLogs.
    -- For data coming from a single resource this array will typically contain one
    -- element. Intermediary nodes (such as OpenTelemetry Collector) that receive
    -- data from multiple origins typically batch the data before forwarding further and
    -- in that case this array will contain multiple elements.
  , exportLogsServiceRequestUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultExportLogsServiceRequest :: ExportLogsServiceRequest
defaultExportLogsServiceRequest = ExportLogsServiceRequest
  { exportLogsServiceRequestResourceLogs = V.empty
  , exportLogsServiceRequestUnknownFields = []
  }

instance MessageEncode ExportLogsServiceRequest where
  buildMessage msg =
    V.foldl' (\acc v -> let sz = messageSize v in acc <> archSubmessage 10 sz (buildMessage v)) mempty msg.exportLogsServiceRequestResourceLogs
    <> encodeUnknownFields msg.exportLogsServiceRequestUnknownFields

instance MessageSize ExportLogsServiceRequest where
  messageSize msg =
    (V.foldl' (\acc v -> acc + archSubmessageSize (messageSize v)) 0 msg.exportLogsServiceRequestResourceLogs)
    + unknownFieldsSize msg.exportLogsServiceRequestUnknownFields

instance MessageDecode ExportLogsServiceRequest where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop V.empty []
    where
      loop acc_0 acc_unknown_ = withTagM
        (pure (ExportLogsServiceRequest {exportLogsServiceRequestResourceLogs = acc_0, exportLogsServiceRequestUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldMessage
            loop (acc_0 <> V.singleton v) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 (uf : acc_unknown_))

instance ProtoMessage ExportLogsServiceRequest where
  protoMessageName _ = "opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest"
  protoPackageName _ = "opentelemetry.proto.collector.logs.v1"
  protoDefaultValue = defaultExportLogsServiceRequest
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "resource_logs"
        , fdNumber = 1
        , fdTypeDesc = MessageType "opentelemetry.proto.logs.v1.ResourceLogs"
        , fdLabel = LabelRepeated
        , fdGet = exportLogsServiceRequestResourceLogs
        , fdSet = \v m -> m { exportLogsServiceRequestResourceLogs = v }
        })
    ]

instance IsMessage ExportLogsServiceRequest

instance Aeson.ToJSON ExportLogsServiceRequest where
  toJSON msg = jsonObject
      [ "resourceLogs" .=: msg.exportLogsServiceRequestResourceLogs

      ]

instance Aeson.FromJSON ExportLogsServiceRequest where
  parseJSON = Aeson.withObject "ExportLogsServiceRequest" $ \obj -> do
    fld_exportLogsServiceRequestResourceLogs <- parseFieldMaybe obj "resourceLogs"
    pure defaultExportLogsServiceRequest
      { exportLogsServiceRequestResourceLogs = maybe (exportLogsServiceRequestResourceLogs defaultExportLogsServiceRequest) id fld_exportLogsServiceRequestResourceLogs
      , exportLogsServiceRequestUnknownFields = []
      }

instance Hashable ExportLogsServiceRequest where
  hashWithSalt salt msg = V.foldl' hashWithSalt (salt) msg.exportLogsServiceRequestResourceLogs

instance Proto.Extension.HasExtensions ExportLogsServiceRequest where
  messageUnknownFields = exportLogsServiceRequestUnknownFields
  setMessageUnknownFields !ufs msg = msg { exportLogsServiceRequestUnknownFields = ufs }

instance Semigroup ExportLogsServiceRequest where
  a <> b = ExportLogsServiceRequest
    { exportLogsServiceRequestResourceLogs = a.exportLogsServiceRequestResourceLogs <> b.exportLogsServiceRequestResourceLogs
    , exportLogsServiceRequestUnknownFields = a.exportLogsServiceRequestUnknownFields <> b.exportLogsServiceRequestUnknownFields
    }

instance Monoid ExportLogsServiceRequest where
  mempty = defaultExportLogsServiceRequest

data ExportLogsServiceResponse = ExportLogsServiceResponse
  { exportLogsServiceResponsePartialSuccess :: !(Maybe ExportLogsPartialSuccess)
    -- ^ The details of a partially successful export request.
    -- 
    -- If the request is only partially accepted
    -- (i.e. when the server accepts only parts of the data and rejects the rest)
    -- the server MUST initialize the `partial_success` field and MUST
    -- set the `rejected_<signal>` with the number of items it rejected.
    -- 
    -- Servers MAY also make use of the `partial_success` field to convey
    -- warnings/suggestions to senders even when the request was fully accepted.
    -- In such cases, the `rejected_<signal>` MUST have a value of `0` and
    -- the `error_message` MUST be non-empty.
    -- 
    -- A `partial_success` message with an empty value (rejected_<signal> = 0 and
    -- `error_message` = "") is equivalent to it not being set/present. Senders
    -- SHOULD interpret it the same way as in the full success case.
  , exportLogsServiceResponseUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultExportLogsServiceResponse :: ExportLogsServiceResponse
defaultExportLogsServiceResponse = ExportLogsServiceResponse
  { exportLogsServiceResponsePartialSuccess = Nothing
  , exportLogsServiceResponseUnknownFields = []
  }

instance MessageEncode ExportLogsServiceResponse where
  buildMessage msg =
    (maybe mempty (\v -> let sz = messageSize v in archSubmessage 10 sz (buildMessage v)) msg.exportLogsServiceResponsePartialSuccess)
    <> encodeUnknownFields msg.exportLogsServiceResponseUnknownFields

instance MessageSize ExportLogsServiceResponse where
  messageSize msg =
    (maybe 0 (\v -> archSubmessageSize (messageSize v)) msg.exportLogsServiceResponsePartialSuccess)
    + unknownFieldsSize msg.exportLogsServiceResponseUnknownFields

instance MessageDecode ExportLogsServiceResponse where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop Nothing []
    where
      loop acc_0 acc_unknown_ = withTagM
        (pure (ExportLogsServiceResponse {exportLogsServiceResponsePartialSuccess = acc_0, exportLogsServiceResponseUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldMessage
            loop (Just v) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 (uf : acc_unknown_))

instance ProtoMessage ExportLogsServiceResponse where
  protoMessageName _ = "opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse"
  protoPackageName _ = "opentelemetry.proto.collector.logs.v1"
  protoDefaultValue = defaultExportLogsServiceResponse
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "partial_success"
        , fdNumber = 1
        , fdTypeDesc = MessageType "ExportLogsPartialSuccess"
        , fdLabel = LabelOptional
        , fdGet = exportLogsServiceResponsePartialSuccess
        , fdSet = \v m -> m { exportLogsServiceResponsePartialSuccess = v }
        })
    ]

instance IsMessage ExportLogsServiceResponse

instance Aeson.ToJSON ExportLogsServiceResponse where
  toJSON msg = jsonObject
      [ "partialSuccess" .=: msg.exportLogsServiceResponsePartialSuccess

      ]

instance Aeson.FromJSON ExportLogsServiceResponse where
  parseJSON = Aeson.withObject "ExportLogsServiceResponse" $ \obj -> do
    fld_exportLogsServiceResponsePartialSuccess <- parseFieldMaybe obj "partialSuccess"
    pure defaultExportLogsServiceResponse
      { exportLogsServiceResponsePartialSuccess = maybe (exportLogsServiceResponsePartialSuccess defaultExportLogsServiceResponse) id fld_exportLogsServiceResponsePartialSuccess
      , exportLogsServiceResponseUnknownFields = []
      }

instance Hashable ExportLogsServiceResponse where
  hashWithSalt salt msg = hashWithSalt (salt) msg.exportLogsServiceResponsePartialSuccess

instance Proto.Extension.HasExtensions ExportLogsServiceResponse where
  messageUnknownFields = exportLogsServiceResponseUnknownFields
  setMessageUnknownFields !ufs msg = msg { exportLogsServiceResponseUnknownFields = ufs }

instance Semigroup ExportLogsServiceResponse where
  a <> b = ExportLogsServiceResponse
    { exportLogsServiceResponsePartialSuccess = case b.exportLogsServiceResponsePartialSuccess of { Nothing -> a.exportLogsServiceResponsePartialSuccess; x -> x }
    , exportLogsServiceResponseUnknownFields = a.exportLogsServiceResponseUnknownFields <> b.exportLogsServiceResponseUnknownFields
    }

instance Monoid ExportLogsServiceResponse where
  mempty = defaultExportLogsServiceResponse

data ExportLogsPartialSuccess = ExportLogsPartialSuccess
  { exportLogsPartialSuccessRejectedLogRecords :: {-# UNPACK #-} !Int64
    -- ^ The number of rejected log records.
    -- 
    -- A `rejected_<signal>` field holding a `0` value indicates that the
    -- request was fully accepted.
  , exportLogsPartialSuccessErrorMessage :: !Text
    -- ^ A developer-facing human-readable message in English. It should be used
    -- either to explain why the server rejected parts of the data during a partial
    -- success or to convey warnings/suggestions during a full success. The message
    -- should offer guidance on how users can address such issues.
    -- 
    -- error_message is an optional field. An error_message with an empty value
    -- is equivalent to it not being set.
  , exportLogsPartialSuccessUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultExportLogsPartialSuccess :: ExportLogsPartialSuccess
defaultExportLogsPartialSuccess = ExportLogsPartialSuccess
  { exportLogsPartialSuccessRejectedLogRecords = 0
  , exportLogsPartialSuccessErrorMessage = ""
  , exportLogsPartialSuccessUnknownFields = []
  }

instance MessageEncode ExportLogsPartialSuccess where
  buildMessage msg =
    (if msg.exportLogsPartialSuccessRejectedLogRecords == 0 then mempty else archVarint 8 (fromIntegral msg.exportLogsPartialSuccessRejectedLogRecords))
    <> (if msg.exportLogsPartialSuccessErrorMessage == T.empty then mempty else archString 18 msg.exportLogsPartialSuccessErrorMessage)
    <> encodeUnknownFields msg.exportLogsPartialSuccessUnknownFields

instance MessageSize ExportLogsPartialSuccess where
  messageSize msg =
    (if msg.exportLogsPartialSuccessRejectedLogRecords == 0 then 0 else archVarintSize (fromIntegral msg.exportLogsPartialSuccessRejectedLogRecords))
    + (if msg.exportLogsPartialSuccessErrorMessage == T.empty then 0 else archStringSize msg.exportLogsPartialSuccessErrorMessage)
    + unknownFieldsSize msg.exportLogsPartialSuccessUnknownFields

instance MessageDecode ExportLogsPartialSuccess where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop 0 "" []
    where
      loop acc_0 acc_1 acc_unknown_ = withTagM
        (pure (ExportLogsPartialSuccess {exportLogsPartialSuccessRejectedLogRecords = acc_0, exportLogsPartialSuccessErrorMessage = acc_1, exportLogsPartialSuccessUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop v acc_1 acc_unknown_
          2 -> do
            v <- decodeFieldString
            loop acc_0 v acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 acc_1 (uf : acc_unknown_))

instance ProtoMessage ExportLogsPartialSuccess where
  protoMessageName _ = "opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess"
  protoPackageName _ = "opentelemetry.proto.collector.logs.v1"
  protoDefaultValue = defaultExportLogsPartialSuccess
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "rejected_log_records"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int64Field
        , fdLabel = LabelOptional
        , fdGet = exportLogsPartialSuccessRejectedLogRecords
        , fdSet = \v m -> m { exportLogsPartialSuccessRejectedLogRecords = v }
        }), (2, SomeField FieldDescriptor
        { fdName = "error_message"
        , fdNumber = 2
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelOptional
        , fdGet = exportLogsPartialSuccessErrorMessage
        , fdSet = \v m -> m { exportLogsPartialSuccessErrorMessage = v }
        })
    ]

instance IsMessage ExportLogsPartialSuccess

instance Aeson.ToJSON ExportLogsPartialSuccess where
  toJSON msg = jsonObject
      [ "rejectedLogRecords" .=: msg.exportLogsPartialSuccessRejectedLogRecords
      , "errorMessage" .=: msg.exportLogsPartialSuccessErrorMessage
      ]

instance Aeson.FromJSON ExportLogsPartialSuccess where
  parseJSON = Aeson.withObject "ExportLogsPartialSuccess" $ \obj -> do
    fld_exportLogsPartialSuccessRejectedLogRecords <- parseFieldMaybe obj "rejectedLogRecords"
    fld_exportLogsPartialSuccessErrorMessage <- parseFieldMaybe obj "errorMessage"
    pure defaultExportLogsPartialSuccess
      { exportLogsPartialSuccessRejectedLogRecords = maybe (exportLogsPartialSuccessRejectedLogRecords defaultExportLogsPartialSuccess) id fld_exportLogsPartialSuccessRejectedLogRecords
      , exportLogsPartialSuccessErrorMessage = maybe (exportLogsPartialSuccessErrorMessage defaultExportLogsPartialSuccess) id fld_exportLogsPartialSuccessErrorMessage
      , exportLogsPartialSuccessUnknownFields = []
      }

instance Hashable ExportLogsPartialSuccess where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (salt) msg.exportLogsPartialSuccessRejectedLogRecords) msg.exportLogsPartialSuccessErrorMessage

instance Proto.Extension.HasExtensions ExportLogsPartialSuccess where
  messageUnknownFields = exportLogsPartialSuccessUnknownFields
  setMessageUnknownFields !ufs msg = msg { exportLogsPartialSuccessUnknownFields = ufs }

instance Semigroup ExportLogsPartialSuccess where
  a <> b = ExportLogsPartialSuccess
    { exportLogsPartialSuccessRejectedLogRecords = if b.exportLogsPartialSuccessRejectedLogRecords == 0 then a.exportLogsPartialSuccessRejectedLogRecords else b.exportLogsPartialSuccessRejectedLogRecords
    , exportLogsPartialSuccessErrorMessage = if b.exportLogsPartialSuccessErrorMessage == "" then a.exportLogsPartialSuccessErrorMessage else b.exportLogsPartialSuccessErrorMessage
    , exportLogsPartialSuccessUnknownFields = a.exportLogsPartialSuccessUnknownFields <> b.exportLogsPartialSuccessUnknownFields
    }

instance Monoid ExportLogsPartialSuccess where
  mempty = defaultExportLogsPartialSuccess