_common/lib: !include "../../package-common.yaml"

name:                hs-opentelemetry-instrumentation-yesod
version:             0.1.1.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Yesod middleware for providing OpenTelemetry instrumentation
category:            OpenTelemetry, Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/instrumentation/yesod#readme>

dependencies:
- base >= 4.7 && < 5

library:
  ghc-options: -Wall
  source-dirs: src
  dependencies:
  - hs-opentelemetry-api ^>= 0.2
  - hs-opentelemetry-instrumentation-wai >= 0.0.1 && < 0.2
  - microlens
  - template-haskell
  - text
  - unliftio
  - unordered-containers
  - wai
  - yesod-core

# Test suite not yet implemented
_tests:
  hs-opentelemetry-instrumentation-yesod-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-opentelemetry-instrumentation-yesod
