_common/lib: !include "../../package-common.yaml"

name:                hs-opentelemetry-instrumentation-yesod
version:             1.0.0.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Yesod middleware for providing OpenTelemetry instrumentation
category:            OpenTelemetry, Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/instrumentation/yesod#readme>

dependencies:
- base >= 4.7 && < 5

library:
  ghc-options: -Wall
  source-dirs: src
  dependencies:
  - hs-opentelemetry-api ^>= 1.0
  - hs-opentelemetry-semantic-conventions >= 1.40 && < 2
  - hs-opentelemetry-instrumentation-wai ^>= 1.0
  - microlens
  - template-haskell
  - text
  - unliftio
  - unordered-containers
  - wai
  - yesod-core

tests:
  hs-opentelemetry-instrumentation-yesod-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - TestApp.ApiSub
    - TestApp.ApiSub.Routes
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-opentelemetry-instrumentation-yesod ^>= 1.0
    - hs-opentelemetry-instrumentation-wai ^>= 1.0
    - hs-opentelemetry-api ^>= 1.0
    - hs-opentelemetry-sdk ^>= 1.0
    - hs-opentelemetry-exporter-in-memory ^>= 1.0
    - hs-opentelemetry-semantic-conventions >= 1.40 && < 2
    - hspec
    - text
    - wai
    - http-types
    - vault
    - network
    - yesod-core
    - template-haskell
    - unordered-containers
