_common/lib: !include "../../package-common.yaml"

name:                hs-opentelemetry-instrumentation-wai
version:             0.1.0.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            WAI instrumentation middleware for OpenTelemetry
category:            OpenTelemetry, Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/instrumentation/wai#readme>

dependencies:
- base >= 4.7 && < 5
- http-types
- wai
- hs-opentelemetry-api == 0.1.*
- vault
- text
- bytestring
- network
- iproute
- unordered-containers

library:
  ghc-options: -Wall
  source-dirs: src

tests:
  hs-opentelemetry-instrumentation-wai-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-opentelemetry-instrumentation-wai
