name:                 thread-utils-finalizers
version:              0.1.1.0
visibility:           public
id:                   thread-utils-finalizers-0.1.1.0-inplace
key:                  thread-utils-finalizers-0.1.1.0-inplace
license:              BSD-3-Clause
copyright:            2021 Ian Duncan
maintainer:           ian@iankduncan.com
author:               Ian Duncan
homepage:             https://github.com/iand675/thread-utils#readme
synopsis:             Perform finalization for threads.
description:
    Please see the README on GitHub at <https://github.com/iand675/thread-finalizers#readme>

category:             Concurrency
abi:                  inplace
exposed:              True
exposed-modules:      Control.Concurrent.Thread.Finalizers
hidden-modules:       Paths_thread_utils_finalizers
import-dirs:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-finalizers-0.1.1.0/build

library-dirs:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-finalizers-0.1.1.0/build

library-dirs-static:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-finalizers-0.1.1.0/build

dynamic-library-dirs:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-finalizers-0.1.1.0/build

data-dir:
    /Users/ian/Code/mercury/hs-opentelemetry/../thread-utils/thread-utils-finalizers/.

hs-libraries:         HSthread-utils-finalizers-0.1.1.0-inplace
depends:              base-4.19.2.0-1e06 ghc-prim-0.11.0-9ad2
haddock-interfaces:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-finalizers-0.1.1.0/doc/html/thread-utils-finalizers/thread-utils-finalizers.haddock

haddock-html:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-finalizers-0.1.1.0/doc/html/thread-utils-finalizers
