name:                hs-opentelemetry-exporter-handle
version:             0.0.1.2
github:              "iand675/hs-opentelemetry"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Handle-based exporter for OpenTelemetry (e.g. stdout)
category: OpenTelemetry, Telemetry, Monitoring

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/exporters/handle#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - OpenTelemetry.Exporter.Handle
  - OpenTelemetry.Exporter.Handle.LogRecord
  - OpenTelemetry.Exporter.Handle.Metric
  - OpenTelemetry.Exporter.Handle.Span
  dependencies:
  - hs-opentelemetry-api ^>= 0.4
  - text
  - vector

tests:
  hs-opentelemetry-exporter-handle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-opentelemetry-exporter-handle >= 0.0.1 && < 0.1
    - hs-opentelemetry-api == 0.4.*
    - hspec
    - unordered-containers
    - vector
