name: otlp-demo

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  otlp-demo:
    main: Main.hs
    source-dirs: src
    dependencies:
      - containers
      - text
      - unordered-containers
      - hs-opentelemetry-api ^>= 1.0
      - hs-opentelemetry-sdk ^>= 1.0
