_common/lib: !include "../../package-common.yaml"

name:                hs-opentelemetry-instrumentation-http-client
version:             0.1.0.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/instrumentation/http-client#readme>

dependencies:
- base >= 4.7 && < 5
- case-insensitive
- conduit
- http-client
- http-client-tls
- http-conduit
- http-types
- hs-opentelemetry-api == 0.1.*
- text
- bytestring
- unliftio
- aeson
- hs-opentelemetry-instrumentation-conduit >= 0.0.1 && < 0.2
- unordered-containers

library:
  ghc-options: -Wall
  source-dirs: src

tests:
  hs-opentelemetry-instrumentation-http-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-opentelemetry-instrumentation-http-client
