_common/lib: !include "../../package-common.yaml"

name:                hs-opentelemetry-utils-exceptions
version:             0.1.0.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/instrumentation/cloudflare#readme>

dependencies:
- base >= 4.7 && < 5
- hs-opentelemetry-api == 0.0.3.*
- hs-opentelemetry-sdk == 0.0.3.*
# - case-insensitive
- text
- exceptions

library:
  source-dirs: src

tests:
  cloudflare-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
