_common/lib: !include "../package-common.yaml"

name:                hs-opentelemetry-otlp
version:             0.0.1.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md
- ../proto/**/*/*.proto

synopsis:            OpenTelemetry protocol buffer modules generated for the OTLP protocol by the proto-lens package
category:            OpenTelemetry

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry#readme>

custom-setup:
  dependencies:
  - base >= 4.7 && < 5
  - Cabal
  - proto-lens-setup
  - Glob

build-tools: proto-lens-protoc:proto-lens-protoc

dependencies:
- base >= 4.7 && < 5
- proto-lens
- proto-lens-runtime

library:
  source-dirs: src
