name:                otel-exporter-zipkin
version:             0.1.0.0
github:              "iand675/otel-exporter-zipkin"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/otel-exporter-zipkin#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  otel-exporter-zipkin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - otel-exporter-zipkin
