_common/lib: !include "../../package-common.yaml"

name:                hs-opentelemetry-instrumentation-postgresql-simple
version:             0.2.0.1

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/instrumentation/postgresql-simple#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - hs-opentelemetry-api ^>= 0.3
  - iproute
  - postgresql-simple
  - postgresql-libpq
  - text
  - bytestring
  - unliftio-core
  - unliftio # todo, unliftio-core
  - unordered-containers

# Test suite not yet implemented
_tests:
  hs-opentelemetry-instrumentation-postgresql-simple-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-opentelemetry-instrumentation-postgresql-simple
