{- HLINT ignore -}
{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# OPTIONS_GHC -Wno-unused-imports -Wno-unused-matches -Wno-unused-top-binds #-}
-- | Auto-generated protobuf types from package @opentelemetry.proto.collector.trace.v1@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.OpenTelemetry.Proto.Collector.Trace.V1.TraceService where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Wireform.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.Internal.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe, protoBytesToJSON)
import Data.Proxy (Proxy(..))
import Data.Reflection (Given(..), given)
import Proto.Internal.JSON.Extension qualified as PJExt
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import Proto.Registry (IsMessage)
import Proto.Registry qualified
import qualified Proto.Extension
import Proto.Internal.Wire (Tag(..), WireType(..))
import Proto.Internal.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Internal.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage,
  archVarintSize, archStringSize, archBytesSize, archBoolSize,
  archFixed32Size, archFixed64Size, archSubmessageSize)
import qualified Proto.OpenTelemetry.Proto.Trace.V1.Trace as OT_Proto_Trace_V1_Trace

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x3a\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2f\x70\x72\x6f\x74\x6f\x2f\x63\x6f\x6c\x6c\x65\x63\x74\x6f\x72\x2f\x74\x72\x61\x63\x65\x2f\x76\x31\x2f\x74\x72\x61\x63\x65\x5f\x73\x65\x72\x76\x69\x63\x65\x2e\x70\x72\x6f\x74\x6f\x12\x26\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2e\x70\x72\x6f\x74\x6f\x2e\x63\x6f\x6c\x6c\x65\x63\x74\x6f\x72\x2e\x74\x72\x61\x63\x65\x2e\x76\x31\x1a\x28\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2f\x70\x72\x6f\x74\x6f\x2f\x74\x72\x61\x63\x65\x2f\x76\x31\x2f\x74\x72\x61\x63\x65\x2e\x70\x72\x6f\x74\x6f\x22\x5f\x0a\x19\x45\x78\x70\x6f\x72\x74\x54\x72\x61\x63\x65\x53\x65\x72\x76\x69\x63\x65\x52\x65\x71\x75\x65\x73\x74\x12\x42\x0a\x0e\x72\x65\x73\x6f\x75\x72\x63\x65\x5f\x73\x70\x61\x6e\x73\x18\x01\x20\x03\x28\x0b\x32\x2a\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2e\x70\x72\x6f\x74\x6f\x2e\x74\x72\x61\x63\x65\x2e\x76\x31\x2e\x52\x65\x73\x6f\x75\x72\x63\x65\x53\x70\x61\x6e\x73\x22\x50\x0a\x1a\x45\x78\x70\x6f\x72\x74\x54\x72\x61\x63\x65\x53\x65\x72\x76\x69\x63\x65\x52\x65\x73\x70\x6f\x6e\x73\x65\x12\x32\x0a\x0f\x70\x61\x72\x74\x69\x61\x6c\x5f\x73\x75\x63\x63\x65\x73\x73\x18\x01\x20\x01\x28\x0b\x32\x19\x45\x78\x70\x6f\x72\x74\x54\x72\x61\x63\x65\x50\x61\x72\x74\x69\x61\x6c\x53\x75\x63\x63\x65\x73\x73\x22\x4a\x0a\x19\x45\x78\x70\x6f\x72\x74\x54\x72\x61\x63\x65\x50\x61\x72\x74\x69\x61\x6c\x53\x75\x63\x63\x65\x73\x73\x12\x16\x0a\x0e\x72\x65\x6a\x65\x63\x74\x65\x64\x5f\x73\x70\x61\x6e\x73\x18\x01\x20\x01\x28\x03\x12\x15\x0a\x0d\x65\x72\x72\x6f\x72\x5f\x6d\x65\x73\x73\x61\x67\x65\x18\x02\x20\x01\x28\x09\x32\x4f\x0a\x0c\x54\x72\x61\x63\x65\x53\x65\x72\x76\x69\x63\x65\x12\x3f\x0a\x06\x45\x78\x70\x6f\x72\x74\x12\x19\x45\x78\x70\x6f\x72\x74\x54\x72\x61\x63\x65\x53\x65\x72\x76\x69\x63\x65\x52\x65\x71\x75\x65\x73\x74\x1a\x1a\x45\x78\x70\x6f\x72\x74\x54\x72\x61\x63\x65\x53\x65\x72\x76\x69\x63\x65\x52\x65\x73\x70\x6f\x6e\x73\x65\x62\x06\x70\x72\x6f\x74\x6f\x33"


-- | Service that can be used to push spans between one Application instrumented with
-- OpenTelemetry and a collector, or between a collector and a central collector (in this
-- case spans are sent/received to/from multiple Applications).
--
-- gRPC service @opentelemetry.proto.collector.trace.v1.TraceService@.
--
-- Methods:
-- * Export (ExportTraceServiceRequest -> ExportTraceServiceResponse)
-- | Server handler record for @TraceService@.
-- Each field is a handler function for one RPC method.
-- Implement all fields to create a server.
data TraceServiceServer m = TraceServiceServer
  { exportHandler :: ExportTraceServiceRequest -> m ExportTraceServiceResponse
  }

-- | Client stub record for @TraceService@.
-- Each field is a function for calling one RPC method.
data TraceServiceClient m = TraceServiceClient
  { export :: ExportTraceServiceRequest -> m ExportTraceServiceResponse
  }

-- | Method metadata for @TraceService@.
data TraceServiceMethod
  = ExportMethod
  deriving stock (Show, Eq, Ord, Enum, Bounded)

traceserviceMethodName :: TraceServiceMethod -> Text
traceserviceMethodName ExportMethod = "Export"

-- | Fully-qualified service name: @TraceService@
traceserviceServiceName :: Text
traceserviceServiceName = "TraceService"

-- | All method paths for @TraceService@.
traceserviceMethodPaths :: [Text]
traceserviceMethodPaths = ["/TraceService/Export"]

data ExportTraceServiceRequest = ExportTraceServiceRequest
  { exportTraceServiceRequestResourceSpans :: !(V.Vector OT_Proto_Trace_V1_Trace.ResourceSpans)
    -- ^ An array of ResourceSpans.
    -- For data coming from a single resource this array will typically contain one
    -- element. Intermediary nodes (such as OpenTelemetry Collector) that receive
    -- data from multiple origins typically batch the data before forwarding further and
    -- in that case this array will contain multiple elements.
  , exportTraceServiceRequestUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultExportTraceServiceRequest :: ExportTraceServiceRequest
defaultExportTraceServiceRequest = ExportTraceServiceRequest
  { exportTraceServiceRequestResourceSpans = V.empty
  , exportTraceServiceRequestUnknownFields = []
  }

instance MessageEncode ExportTraceServiceRequest where
  buildMessage msg =
    V.foldl' (\acc v -> let sz = messageSize v in acc <> archSubmessage 10 sz (buildMessage v)) mempty msg.exportTraceServiceRequestResourceSpans
    <> encodeUnknownFields msg.exportTraceServiceRequestUnknownFields

instance MessageSize ExportTraceServiceRequest where
  messageSize msg =
    (V.foldl' (\acc v -> acc + archSubmessageSize (messageSize v)) 0 msg.exportTraceServiceRequestResourceSpans)
    + unknownFieldsSize msg.exportTraceServiceRequestUnknownFields

instance MessageDecode ExportTraceServiceRequest where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop V.empty []
    where
      loop acc_0 acc_unknown_ = withTagM
        (pure (ExportTraceServiceRequest {exportTraceServiceRequestResourceSpans = acc_0, exportTraceServiceRequestUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldMessage
            loop (acc_0 <> V.singleton v) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 (uf : acc_unknown_))

instance ProtoMessage ExportTraceServiceRequest where
  protoMessageName _ = "opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest"
  protoPackageName _ = "opentelemetry.proto.collector.trace.v1"
  protoDefaultValue = defaultExportTraceServiceRequest
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "resource_spans"
        , fdNumber = 1
        , fdTypeDesc = MessageType "opentelemetry.proto.trace.v1.ResourceSpans"
        , fdLabel = LabelRepeated
        , fdGet = exportTraceServiceRequestResourceSpans
        , fdSet = \v m -> m { exportTraceServiceRequestResourceSpans = v }
        })
    ]

instance IsMessage ExportTraceServiceRequest

instance Aeson.ToJSON ExportTraceServiceRequest where
  toJSON msg = jsonObject
      [ "resourceSpans" .=: msg.exportTraceServiceRequestResourceSpans

      ]

instance Aeson.FromJSON ExportTraceServiceRequest where
  parseJSON = Aeson.withObject "ExportTraceServiceRequest" $ \obj -> do
    fld_exportTraceServiceRequestResourceSpans <- parseFieldMaybe obj "resourceSpans"
    pure defaultExportTraceServiceRequest
      { exportTraceServiceRequestResourceSpans = maybe (exportTraceServiceRequestResourceSpans defaultExportTraceServiceRequest) id fld_exportTraceServiceRequestResourceSpans
      , exportTraceServiceRequestUnknownFields = []
      }

instance Hashable ExportTraceServiceRequest where
  hashWithSalt salt msg = V.foldl' hashWithSalt (salt) msg.exportTraceServiceRequestResourceSpans

instance Proto.Extension.HasExtensions ExportTraceServiceRequest where
  messageUnknownFields = exportTraceServiceRequestUnknownFields
  setMessageUnknownFields !ufs msg = msg { exportTraceServiceRequestUnknownFields = ufs }

instance Semigroup ExportTraceServiceRequest where
  a <> b = ExportTraceServiceRequest
    { exportTraceServiceRequestResourceSpans = a.exportTraceServiceRequestResourceSpans <> b.exportTraceServiceRequestResourceSpans
    , exportTraceServiceRequestUnknownFields = a.exportTraceServiceRequestUnknownFields <> b.exportTraceServiceRequestUnknownFields
    }

instance Monoid ExportTraceServiceRequest where
  mempty = defaultExportTraceServiceRequest

data ExportTraceServiceResponse = ExportTraceServiceResponse
  { exportTraceServiceResponsePartialSuccess :: !(Maybe ExportTracePartialSuccess)
    -- ^ The details of a partially successful export request.
    -- 
    -- If the request is only partially accepted
    -- (i.e. when the server accepts only parts of the data and rejects the rest)
    -- the server MUST initialize the `partial_success` field and MUST
    -- set the `rejected_<signal>` with the number of items it rejected.
    -- 
    -- Servers MAY also make use of the `partial_success` field to convey
    -- warnings/suggestions to senders even when the request was fully accepted.
    -- In such cases, the `rejected_<signal>` MUST have a value of `0` and
    -- the `error_message` MUST be non-empty.
    -- 
    -- A `partial_success` message with an empty value (rejected_<signal> = 0 and
    -- `error_message` = "") is equivalent to it not being set/present. Senders
    -- SHOULD interpret it the same way as in the full success case.
  , exportTraceServiceResponseUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultExportTraceServiceResponse :: ExportTraceServiceResponse
defaultExportTraceServiceResponse = ExportTraceServiceResponse
  { exportTraceServiceResponsePartialSuccess = Nothing
  , exportTraceServiceResponseUnknownFields = []
  }

instance MessageEncode ExportTraceServiceResponse where
  buildMessage msg =
    (maybe mempty (\v -> let sz = messageSize v in archSubmessage 10 sz (buildMessage v)) msg.exportTraceServiceResponsePartialSuccess)
    <> encodeUnknownFields msg.exportTraceServiceResponseUnknownFields

instance MessageSize ExportTraceServiceResponse where
  messageSize msg =
    (maybe 0 (\v -> archSubmessageSize (messageSize v)) msg.exportTraceServiceResponsePartialSuccess)
    + unknownFieldsSize msg.exportTraceServiceResponseUnknownFields

instance MessageDecode ExportTraceServiceResponse where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop Nothing []
    where
      loop acc_0 acc_unknown_ = withTagM
        (pure (ExportTraceServiceResponse {exportTraceServiceResponsePartialSuccess = acc_0, exportTraceServiceResponseUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldMessage
            loop (Just v) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 (uf : acc_unknown_))

instance ProtoMessage ExportTraceServiceResponse where
  protoMessageName _ = "opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse"
  protoPackageName _ = "opentelemetry.proto.collector.trace.v1"
  protoDefaultValue = defaultExportTraceServiceResponse
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "partial_success"
        , fdNumber = 1
        , fdTypeDesc = MessageType "ExportTracePartialSuccess"
        , fdLabel = LabelOptional
        , fdGet = exportTraceServiceResponsePartialSuccess
        , fdSet = \v m -> m { exportTraceServiceResponsePartialSuccess = v }
        })
    ]

instance IsMessage ExportTraceServiceResponse

instance Aeson.ToJSON ExportTraceServiceResponse where
  toJSON msg = jsonObject
      [ "partialSuccess" .=: msg.exportTraceServiceResponsePartialSuccess

      ]

instance Aeson.FromJSON ExportTraceServiceResponse where
  parseJSON = Aeson.withObject "ExportTraceServiceResponse" $ \obj -> do
    fld_exportTraceServiceResponsePartialSuccess <- parseFieldMaybe obj "partialSuccess"
    pure defaultExportTraceServiceResponse
      { exportTraceServiceResponsePartialSuccess = maybe (exportTraceServiceResponsePartialSuccess defaultExportTraceServiceResponse) id fld_exportTraceServiceResponsePartialSuccess
      , exportTraceServiceResponseUnknownFields = []
      }

instance Hashable ExportTraceServiceResponse where
  hashWithSalt salt msg = hashWithSalt (salt) msg.exportTraceServiceResponsePartialSuccess

instance Proto.Extension.HasExtensions ExportTraceServiceResponse where
  messageUnknownFields = exportTraceServiceResponseUnknownFields
  setMessageUnknownFields !ufs msg = msg { exportTraceServiceResponseUnknownFields = ufs }

instance Semigroup ExportTraceServiceResponse where
  a <> b = ExportTraceServiceResponse
    { exportTraceServiceResponsePartialSuccess = case b.exportTraceServiceResponsePartialSuccess of { Nothing -> a.exportTraceServiceResponsePartialSuccess; x -> x }
    , exportTraceServiceResponseUnknownFields = a.exportTraceServiceResponseUnknownFields <> b.exportTraceServiceResponseUnknownFields
    }

instance Monoid ExportTraceServiceResponse where
  mempty = defaultExportTraceServiceResponse

data ExportTracePartialSuccess = ExportTracePartialSuccess
  { exportTracePartialSuccessRejectedSpans :: {-# UNPACK #-} !Int64
    -- ^ The number of rejected spans.
    -- 
    -- A `rejected_<signal>` field holding a `0` value indicates that the
    -- request was fully accepted.
  , exportTracePartialSuccessErrorMessage :: !Text
    -- ^ A developer-facing human-readable message in English. It should be used
    -- either to explain why the server rejected parts of the data during a partial
    -- success or to convey warnings/suggestions during a full success. The message
    -- should offer guidance on how users can address such issues.
    -- 
    -- error_message is an optional field. An error_message with an empty value
    -- is equivalent to it not being set.
  , exportTracePartialSuccessUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultExportTracePartialSuccess :: ExportTracePartialSuccess
defaultExportTracePartialSuccess = ExportTracePartialSuccess
  { exportTracePartialSuccessRejectedSpans = 0
  , exportTracePartialSuccessErrorMessage = ""
  , exportTracePartialSuccessUnknownFields = []
  }

instance MessageEncode ExportTracePartialSuccess where
  buildMessage msg =
    (if msg.exportTracePartialSuccessRejectedSpans == 0 then mempty else archVarint 8 (fromIntegral msg.exportTracePartialSuccessRejectedSpans))
    <> (if msg.exportTracePartialSuccessErrorMessage == T.empty then mempty else archString 18 msg.exportTracePartialSuccessErrorMessage)
    <> encodeUnknownFields msg.exportTracePartialSuccessUnknownFields

instance MessageSize ExportTracePartialSuccess where
  messageSize msg =
    (if msg.exportTracePartialSuccessRejectedSpans == 0 then 0 else archVarintSize (fromIntegral msg.exportTracePartialSuccessRejectedSpans))
    + (if msg.exportTracePartialSuccessErrorMessage == T.empty then 0 else archStringSize msg.exportTracePartialSuccessErrorMessage)
    + unknownFieldsSize msg.exportTracePartialSuccessUnknownFields

instance MessageDecode ExportTracePartialSuccess where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop 0 "" []
    where
      loop acc_0 acc_1 acc_unknown_ = withTagM
        (pure (ExportTracePartialSuccess {exportTracePartialSuccessRejectedSpans = acc_0, exportTracePartialSuccessErrorMessage = acc_1, exportTracePartialSuccessUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop v acc_1 acc_unknown_
          2 -> do
            v <- decodeFieldString
            loop acc_0 v acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 acc_1 (uf : acc_unknown_))

instance ProtoMessage ExportTracePartialSuccess where
  protoMessageName _ = "opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess"
  protoPackageName _ = "opentelemetry.proto.collector.trace.v1"
  protoDefaultValue = defaultExportTracePartialSuccess
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "rejected_spans"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int64Field
        , fdLabel = LabelOptional
        , fdGet = exportTracePartialSuccessRejectedSpans
        , fdSet = \v m -> m { exportTracePartialSuccessRejectedSpans = v }
        }), (2, SomeField FieldDescriptor
        { fdName = "error_message"
        , fdNumber = 2
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelOptional
        , fdGet = exportTracePartialSuccessErrorMessage
        , fdSet = \v m -> m { exportTracePartialSuccessErrorMessage = v }
        })
    ]

instance IsMessage ExportTracePartialSuccess

instance Aeson.ToJSON ExportTracePartialSuccess where
  toJSON msg = jsonObject
      [ "rejectedSpans" .=: msg.exportTracePartialSuccessRejectedSpans
      , "errorMessage" .=: msg.exportTracePartialSuccessErrorMessage
      ]

instance Aeson.FromJSON ExportTracePartialSuccess where
  parseJSON = Aeson.withObject "ExportTracePartialSuccess" $ \obj -> do
    fld_exportTracePartialSuccessRejectedSpans <- parseFieldMaybe obj "rejectedSpans"
    fld_exportTracePartialSuccessErrorMessage <- parseFieldMaybe obj "errorMessage"
    pure defaultExportTracePartialSuccess
      { exportTracePartialSuccessRejectedSpans = maybe (exportTracePartialSuccessRejectedSpans defaultExportTracePartialSuccess) id fld_exportTracePartialSuccessRejectedSpans
      , exportTracePartialSuccessErrorMessage = maybe (exportTracePartialSuccessErrorMessage defaultExportTracePartialSuccess) id fld_exportTracePartialSuccessErrorMessage
      , exportTracePartialSuccessUnknownFields = []
      }

instance Hashable ExportTracePartialSuccess where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (salt) msg.exportTracePartialSuccessRejectedSpans) msg.exportTracePartialSuccessErrorMessage

instance Proto.Extension.HasExtensions ExportTracePartialSuccess where
  messageUnknownFields = exportTracePartialSuccessUnknownFields
  setMessageUnknownFields !ufs msg = msg { exportTracePartialSuccessUnknownFields = ufs }

instance Semigroup ExportTracePartialSuccess where
  a <> b = ExportTracePartialSuccess
    { exportTracePartialSuccessRejectedSpans = if b.exportTracePartialSuccessRejectedSpans == 0 then a.exportTracePartialSuccessRejectedSpans else b.exportTracePartialSuccessRejectedSpans
    , exportTracePartialSuccessErrorMessage = if b.exportTracePartialSuccessErrorMessage == "" then a.exportTracePartialSuccessErrorMessage else b.exportTracePartialSuccessErrorMessage
    , exportTracePartialSuccessUnknownFields = a.exportTracePartialSuccessUnknownFields <> b.exportTracePartialSuccessUnknownFields
    }

instance Monoid ExportTracePartialSuccess where
  mempty = defaultExportTracePartialSuccess