name: yesod-minimal

dependencies:
  - base >= 4.7 && < 5

executables:
  yesod-minimal:
    main: Minimal
    source-dirs: src
    ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      # minimal example dependencies
      - bytestring
      - conduit
      - yesod-core
      - warp
      - text
      - unliftio
      # database
      - yesod-persistent
      - monad-logger
      - persistent >= 2.13.3
      - persistent-postgresql >= 2.13.4
      - persistent-qq
      - resource-pool
      # opentelemetry dependencies
      - hs-opentelemetry-sdk ^>= 1.0
      - hs-opentelemetry-instrumentation-wai ^>= 1.0
      - hs-opentelemetry-instrumentation-yesod ^>= 1.0
      - hs-opentelemetry-instrumentation-http-client ^>= 1.0
      - hs-opentelemetry-instrumentation-persistent ^>= 1.0
      - hs-opentelemetry-instrumentation-postgresql-simple ^>= 1.0
      - hs-opentelemetry-instrumentation-ghc-metrics ^>= 1.0
      - hs-opentelemetry-api ^>= 1.0
