name: yesod-minimal

dependencies:
  - base >= 4.7 && < 5

executables:
  yesod-minimal:
    main: Minimal
    source-dirs: src
    ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      # minimal example dependencies
      - bytestring
      - conduit
      - yesod-core
      - warp
      - text
      - unliftio
      # database
      - yesod-persistent
      - monad-logger
      - persistent >= 2.13.3
      - persistent-postgresql >= 2.13.4
      - persistent-qq
      - resource-pool
      # opentelemetry dependencies
      - hs-opentelemetry-sdk
      - hs-opentelemetry-instrumentation-wai
      - hs-opentelemetry-instrumentation-yesod
      - hs-opentelemetry-instrumentation-http-client
      - hs-opentelemetry-instrumentation-persistent
      - hs-opentelemetry-instrumentation-postgresql-simple
