_common/lib: !include "../../package-common.yaml"

name:                hs-opentelemetry-utils-sqlcommenter
version:             1.0.0.0

<<: *preface

extra-source-files:
- README.md
- CHANGELOG.md

synopsis: SqlCommenter utilities for OpenTelemetry instrumentation
category: OpenTelemetry, Telemetry, Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/utils/sqlcommenter#readme>

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  other-modules:
  - OpenTelemetry.Utils.SqlCommenter.Internal.Compat
  dependencies:
  - bytestring
  - text >= 2.0 && < 2.2
  - attoparsec
  - containers
  - hs-opentelemetry-api ^>= 1.0
  - hs-opentelemetry-propagator-w3c ^>= 1.0
  - http-types

tests:
  sqlcommenter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-opentelemetry-utils-sqlcommenter ^>= 1.0
    - bytestring
    - text
    - containers
    - hspec
    - hspec-hedgehog
    - hedgehog
    - http-types
    - hs-opentelemetry-api ^>= 1.0
    - hs-opentelemetry-exporter-in-memory ^>= 1.0
