name:                 thread-utils-context
version:              0.3.0.4
visibility:           public
id:                   thread-utils-context-0.3.0.4-inplace
key:                  thread-utils-context-0.3.0.4-inplace
license:              BSD-3-Clause
copyright:            2023 Ian Duncan
maintainer:           ian@iankduncan.com
author:               Ian Duncan
homepage:             https://github.com/iand675/thread-utils#readme
synopsis:             Garbage-collected thread local storage
description:
    Please see the README on GitHub at <https://github.com/iand675/thread-utils-context#readme>

category:             Concurrency
abi:                  inplace
exposed:              True
exposed-modules:      Control.Concurrent.Thread.Storage
hidden-modules:       Paths_thread_utils_context
import-dirs:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-context-0.3.0.4/build

library-dirs:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-context-0.3.0.4/build

library-dirs-static:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-context-0.3.0.4/build

dynamic-library-dirs:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-context-0.3.0.4/build

data-dir:
    /Users/ian/Code/mercury/hs-opentelemetry/../thread-utils/thread-utils-context/.

hs-libraries:         HSthread-utils-context-0.3.0.4-inplace
depends:
    base-4.19.2.0-1e06 containers-0.6.8-1965 ghc-prim-0.11.0-9ad2
    thread-utils-finalizers-0.1.1.0-inplace

haddock-interfaces:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-context-0.3.0.4/doc/html/thread-utils-context/thread-utils-context.haddock

haddock-html:
    /Users/ian/Code/mercury/hs-opentelemetry/dist-ghc98/build/aarch64-osx/ghc-9.8.4/thread-utils-context-0.3.0.4/doc/html/thread-utils-context
