_common/lib: !include "../package-common.yaml"

name:                hs-opentelemetry-sdk
version:             0.1.0.1

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md
extra-doc-files:
- docs/img/*

synopsis:            OpenTelemetry SDK for use in applications.
category:            OpenTelemetry, Telemetry, Monitoring, Observability, Metrics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/sdk#readme>

dependencies:
- base >= 4.7 && < 5

library:
  exposed-modules:
  - OpenTelemetry.Configuration
  - OpenTelemetry.Configuration.Create
  - OpenTelemetry.Configuration.Parse
  - OpenTelemetry.Configuration.Types
  - OpenTelemetry.Log
  - OpenTelemetry.MeterProvider
  - OpenTelemetry.Metric
  - OpenTelemetry.Metric.ExporterSelection
  - OpenTelemetry.Metric.View
  - OpenTelemetry.MetricReader
  - OpenTelemetry.Processor.Batch
  - OpenTelemetry.Processor.Batch.LogRecord
  - OpenTelemetry.Processor.Batch.Span
  - OpenTelemetry.Processor.Simple
  - OpenTelemetry.Processor.Simple.LogRecord
  - OpenTelemetry.Processor.Simple.Span
  - OpenTelemetry.Resource.Cloud.Detector
  - OpenTelemetry.Resource.Container.Detector
  - OpenTelemetry.Resource.Detect
  - OpenTelemetry.Resource.Detector.AWS.EC2
  - OpenTelemetry.Resource.Detector.AWS.ECS
  - OpenTelemetry.Resource.Detector.AWS.EKS
  - OpenTelemetry.Resource.Detector.Azure
  - OpenTelemetry.Resource.Detector.GCP
  - OpenTelemetry.Resource.Detector.Heroku
  - OpenTelemetry.Resource.Detector.Metadata
  - OpenTelemetry.Resource.FaaS.Detector
  - OpenTelemetry.Resource.Host.Detector
  - OpenTelemetry.Resource.Kubernetes.Detector
  - OpenTelemetry.Resource.OperatingSystem.Detector
  - OpenTelemetry.Resource.Process.Detector
  - OpenTelemetry.Resource.Service.Detector
  - OpenTelemetry.Resource.Telemetry.Detector
  - OpenTelemetry.Trace
  - OpenTelemetry.Trace.Id.Generator.Default
  ghc-options: -Wall
  source-dirs: src
  when:
    - condition: os(windows)
      then:
        source-dirs: src/platform/windows
      else:
        source-dirs: src/platform/unix
        dependencies: unix # for getEffectiveUserID
  dependencies:
  - aeson
  - async
  - bytestring
  - case-insensitive
  - crypton-connection
  - containers
  - hashable
  - http-client
  - http-client-tls
  - http-types
  - tls
  - crypton-x509-store
  - network-bsd
  - process
  - scientific
  - stm
  - text
  - yaml
  - unix-compat >= 0.7.1 # for getProcessID
  - unordered-containers

  - vector
  - unagi-chan >= 0.4 && < 0.5
  # These are "distribution" packages
  - hs-opentelemetry-api ^>= 0.4
  - hs-opentelemetry-semantic-conventions >= 1.40 && < 2
  - hs-opentelemetry-propagator-w3c ^>= 0.1.0
  - hs-opentelemetry-exporter-handle ^>= 0.0.1
  - hs-opentelemetry-exporter-otlp ^>= 0.1
  - hs-opentelemetry-propagator-b3 ^>=0.0.1
  - hs-opentelemetry-propagator-datadog ^>=0.0.0
  - hs-opentelemetry-propagator-jaeger ^>=0.0.1
  - hs-opentelemetry-propagator-xray ^>=0.0.1
  reexported-modules:
    - OpenTelemetry.Attributes
    - OpenTelemetry.Baggage
    - OpenTelemetry.Context
    - OpenTelemetry.Log.Core
    - OpenTelemetry.Metric.Core
    - OpenTelemetry.Context.Environment
    - OpenTelemetry.Context.ThreadLocal
    - OpenTelemetry.Context.ThreadLocal.Propagation
    - OpenTelemetry.Exporter.Span
    - OpenTelemetry.Exporter.LogRecord
    - OpenTelemetry.Exporter
    - OpenTelemetry.Processor.Span
    - OpenTelemetry.Processor.LogRecord
    - OpenTelemetry.Processor
    - OpenTelemetry.Propagator
    - OpenTelemetry.Resource
    - OpenTelemetry.Resource.Cloud
    - OpenTelemetry.Resource.Container
    - OpenTelemetry.Resource.DeploymentEnvironment
    - OpenTelemetry.Resource.Device
    - OpenTelemetry.Resource.FaaS
    - OpenTelemetry.Resource.Host
    - OpenTelemetry.Resource.Kubernetes
    - OpenTelemetry.Resource.OperatingSystem
    - OpenTelemetry.Resource.Process
    - OpenTelemetry.Resource.Service
    - OpenTelemetry.Resource.Telemetry
    - OpenTelemetry.Resource.Webengine
    # - OpenTelemetry.Trace
    - OpenTelemetry.Trace.Id
    # - OpenTelemetry.Trace.IdGenerator
    - OpenTelemetry.Trace.Monad
    - OpenTelemetry.Trace.Sampler
    - OpenTelemetry.Trace.TraceState
    - OpenTelemetry.Util
  other-modules:
  - Paths_hs_opentelemetry_sdk

tests:
  hs-opentelemetry-sdk-test:
    main:                Spec.hs
    other-modules:
    - OpenTelemetry.BaggageSpec
    - OpenTelemetry.ConfigurationSpec
    - OpenTelemetry.ContextSpec
    - OpenTelemetry.ContextInSpanSpec
    - OpenTelemetry.MeterProviderSpec
    - OpenTelemetry.MetricReaderSpec
    - OpenTelemetry.Resource.DetectorSpec
    - OpenTelemetry.ResourceSpec
    - OpenTelemetry.Trace.CallStackSpec
    - OpenTelemetry.TraceSpec
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: "!os(windows)"
      dependencies: unix
    dependencies:
    - async
    - bytestring
    - containers
    - directory
    - hs-opentelemetry-api == 0.4.*
    - hs-opentelemetry-exporter-in-memory == 0.0.*
    - hs-opentelemetry-propagator-b3 >= 0.0.1 && < 0.1
    - hs-opentelemetry-propagator-w3c >= 0.1.0 && < 0.2
    - hs-opentelemetry-sdk
    - hs-opentelemetry-semantic-conventions >= 1.40 && < 2
    - hspec
    - process
    - text
    - unordered-containers
    - vector
