_common/lib: !include "../package-common.yaml"

name:                hs-opentelemetry-sdk
version:             0.1.0.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md
extra-doc-files:
- docs/img/*

synopsis:            OpenTelemetry SDK for use in applications.
category:            OpenTelemetry, Telemetry, Monitoring, Observability, Metrics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/sdk#readme>

dependencies:
- base >= 4.7 && < 5

library:
  ghc-options: -Wall
  source-dirs: src
  when:
    - condition: os(windows)
      then:
        source-dirs: src/platform/windows
      else:
        source-dirs: src/platform/unix
        dependencies: unix # for getEffectiveUserID
  dependencies:
  - async
  - bytestring
  - http-types
  - network-bsd
  - random >= 1.2.0
  - stm
  - text
  - unagi-chan
  - unix-compat >= 0.7.1 # for getProcessID
  - unordered-containers
  - vector
  - vector-builder
  # These are "distribution" packages
  - hs-opentelemetry-api ^>= 0.2
  - hs-opentelemetry-propagator-w3c ^>= 0.0.1
  - hs-opentelemetry-exporter-otlp ^>= 0.1
  - hs-opentelemetry-propagator-b3 ^>=0.0.1
  - hs-opentelemetry-propagator-datadog ^>=0.0.0
  reexported-modules:
    - OpenTelemetry.Attributes
    - OpenTelemetry.Baggage
    - OpenTelemetry.Context
    - OpenTelemetry.Context.ThreadLocal
    - OpenTelemetry.Exporter.Span
    - OpenTelemetry.Exporter.LogRecord
    - OpenTelemetry.Exporter
    - OpenTelemetry.Processor.Span
    - OpenTelemetry.Processor.LogRecord
    - OpenTelemetry.Processor
    - OpenTelemetry.Propagator
    - OpenTelemetry.Resource
    - OpenTelemetry.Resource.Cloud
    - OpenTelemetry.Resource.Container
    - OpenTelemetry.Resource.DeploymentEnvironment
    - OpenTelemetry.Resource.Device
    - OpenTelemetry.Resource.FaaS
    - OpenTelemetry.Resource.Host
    - OpenTelemetry.Resource.Kubernetes
    - OpenTelemetry.Resource.OperatingSystem
    - OpenTelemetry.Resource.Process
    - OpenTelemetry.Resource.Service
    - OpenTelemetry.Resource.Telemetry
    - OpenTelemetry.Resource.Webengine
    # - OpenTelemetry.Trace
    - OpenTelemetry.Trace.Id
    # - OpenTelemetry.Trace.IdGenerator
    - OpenTelemetry.Trace.Monad
    - OpenTelemetry.Trace.Sampler
    - OpenTelemetry.Trace.TraceState
    - OpenTelemetry.Util
  other-modules:
  - Paths_hs_opentelemetry_sdk

tests:
  hs-opentelemetry-sdk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clock
    - hs-opentelemetry-api
    - hs-opentelemetry-sdk
    - hspec
    - text
    - unordered-containers
