_common/lib: !include "../package-common.yaml"

name:                hs-opentelemetry-api
version:             0.4.0.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            OpenTelemetry API for use by libraries for direct instrumentation or wrapper packages.
category:            OpenTelemetry, Telemetry, Monitoring, Observability, Metrics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/api#readme>

default-extensions:
- OverloadedStrings
- RecordWildCards

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: -Wall
  c-sources:
  - cbits/hs_otel_hex.c
  - cbits/hs_otel_rng.c
  - cbits/hs_otel_time.c
  include-dirs:
  - include
  reexported-modules:
  - OpenTelemetry.Attributes.Attribute
  - OpenTelemetry.Attributes.Key
  dependencies:
  - async
  - bytestring
  - hashable
  - hs-opentelemetry-api-types == 0.1.*
  - hs-opentelemetry-semantic-conventions >= 1.40 && < 2
  - template-haskell
  - text
  - thread-utils-context == 0.3.*
  - transformers
  - unliftio-core
  - unordered-containers
  - vault
  - vector
  other-modules:
  - OpenTelemetry.Context.Types
  - OpenTelemetry.Internal.Metrics.Export
  - OpenTelemetry.Internal.Metrics.Types
  - OpenTelemetry.Internal.Trace.Types
  - OpenTelemetry.Internal.UnpackedMaybe
  - Paths_hs_opentelemetry_api

benchmarks:
  hs-opentelemetry-api-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - containers
    - hs-opentelemetry-api
    - tasty-bench
    - text
    - unordered-containers
    - vector
    - vector-builder

tests:
  hs-opentelemetry-api-test:
    main:                Spec.hs
    other-modules:
    - OpenTelemetry.AttributesSpec
    - OpenTelemetry.BaggageSpec
    - OpenTelemetry.Context.EnvironmentSpec
    - OpenTelemetry.Contrib.CarryOnsSpec
    - OpenTelemetry.Contrib.SpanTraversalsSpec
    - OpenTelemetry.EnvironmentSpec
    - OpenTelemetry.InstrumentationLibrarySpec
    - OpenTelemetry.Logs.CoreSpec
    - OpenTelemetry.MetricsSpec
    - OpenTelemetry.RegistrySpec
    - OpenTelemetry.ResourceSpec
    - OpenTelemetry.SemanticsConfigSpec
    - OpenTelemetry.Trace.ExceptionHandlerSpec
    - OpenTelemetry.Trace.MonadSpec
    - OpenTelemetry.Trace.SamplerSpec
    - OpenTelemetry.Trace.TraceFlagsSpec
    - OpenTelemetry.Trace.TracerSpec
    - OpenTelemetry.Trace.UtilsSpec
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - bytestring
    - hs-opentelemetry-api
    - hspec
    - text
    - transformers
    - unliftio-core
    - unordered-containers
    - vector
