_common/lib: !include "../package-common.yaml"

name:                hs-opentelemetry-api
version:             0.1.0.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            OpenTelemetry API for use by libraries for direct instrumentation or wrapper packages.
category:            OpenTelemetry, Telemetry, Monitoring, Observability, Metrics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/api#readme>

default-extensions:
- OverloadedStrings
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- async
- bytestring
- text
- vault
- containers
- hashable
- thread-utils-context == 0.3.*
- unordered-containers
- binary
- vector
- clock
- memory
- mtl
- transformers
- http-types
- attoparsec
- template-haskell
- charset
- ghc-prim
- unliftio-core
- vector-builder
- safe-exceptions

library:
  source-dirs: src
  ghc-options: -Wall
  other-modules:
  - OpenTelemetry.Context.Types
  - OpenTelemetry.Internal.Trace.Types
  - Paths_hs_opentelemetry_api

tests:
  hs-opentelemetry-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hs-opentelemetry-api
    - vector
    - vector-builder
