{- HLINT ignore -}
{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# OPTIONS_GHC -Wno-unused-imports -Wno-unused-matches -Wno-unused-top-binds #-}
-- | Auto-generated protobuf types from package @opentelemetry.proto.resource.v1@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.OpenTelemetry.Proto.Resource.V1.Resource where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Wireform.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.Internal.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe, protoBytesToJSON)
import Data.Proxy (Proxy(..))
import Data.Reflection (Given(..), given)
import Proto.Internal.JSON.Extension qualified as PJExt
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import Proto.Registry (IsMessage)
import Proto.Registry qualified
import qualified Proto.Extension
import Proto.Internal.Wire (Tag(..), WireType(..))
import Proto.Internal.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Internal.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage,
  archVarintSize, archStringSize, archBytesSize, archBoolSize,
  archFixed32Size, archFixed64Size, archSubmessageSize)
import qualified Proto.OpenTelemetry.Proto.Common.V1.Common as OT_Proto_Common_V1_Common

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x2e\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2f\x70\x72\x6f\x74\x6f\x2f\x72\x65\x73\x6f\x75\x72\x63\x65\x2f\x76\x31\x2f\x72\x65\x73\x6f\x75\x72\x63\x65\x2e\x70\x72\x6f\x74\x6f\x12\x1f\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2e\x70\x72\x6f\x74\x6f\x2e\x72\x65\x73\x6f\x75\x72\x63\x65\x2e\x76\x31\x1a\x2a\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2f\x70\x72\x6f\x74\x6f\x2f\x63\x6f\x6d\x6d\x6f\x6e\x2f\x76\x31\x2f\x63\x6f\x6d\x6d\x6f\x6e\x2e\x70\x72\x6f\x74\x6f\x22\xa6\x01\x0a\x08\x52\x65\x73\x6f\x75\x72\x63\x65\x12\x3a\x0a\x0a\x61\x74\x74\x72\x69\x62\x75\x74\x65\x73\x18\x01\x20\x03\x28\x0b\x32\x26\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2e\x70\x72\x6f\x74\x6f\x2e\x63\x6f\x6d\x6d\x6f\x6e\x2e\x76\x31\x2e\x4b\x65\x79\x56\x61\x6c\x75\x65\x12\x20\x0a\x18\x64\x72\x6f\x70\x70\x65\x64\x5f\x61\x74\x74\x72\x69\x62\x75\x74\x65\x73\x5f\x63\x6f\x75\x6e\x74\x18\x02\x20\x01\x28\x0d\x12\x3c\x0a\x0b\x65\x6e\x74\x69\x74\x79\x5f\x72\x65\x66\x73\x18\x03\x20\x03\x28\x0b\x32\x27\x6f\x70\x65\x6e\x74\x65\x6c\x65\x6d\x65\x74\x72\x79\x2e\x70\x72\x6f\x74\x6f\x2e\x63\x6f\x6d\x6d\x6f\x6e\x2e\x76\x31\x2e\x45\x6e\x74\x69\x74\x79\x52\x65\x66\x62\x06\x70\x72\x6f\x74\x6f\x33"


-- | Resource information.
data Resource = Resource
  { resourceAttributes :: !(V.Vector OT_Proto_Common_V1_Common.KeyValue)
    -- ^ Set of attributes that describe the resource.
    -- Attribute keys MUST be unique (it is not allowed to have more than one
    -- attribute with the same key).
    -- The behavior of software that receives duplicated keys can be unpredictable.
  , resourceDroppedAttributesCount :: {-# UNPACK #-} !Word32
    -- ^ The number of dropped attributes. If the value is 0, then
    -- no attributes were dropped.
  , resourceEntityRefs :: !(V.Vector OT_Proto_Common_V1_Common.EntityRef)
    -- ^ Set of entities that participate in this Resource.
    -- 
    -- Note: keys in the references MUST exist in attributes of this message.
    -- 
    -- Status: [Development]
  , resourceUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultResource :: Resource
defaultResource = Resource
  { resourceAttributes = V.empty
  , resourceDroppedAttributesCount = 0
  , resourceEntityRefs = V.empty
  , resourceUnknownFields = []
  }

instance MessageEncode Resource where
  buildMessage msg =
    V.foldl' (\acc v -> let sz = messageSize v in acc <> archSubmessage 10 sz (buildMessage v)) mempty msg.resourceAttributes
    <> (if msg.resourceDroppedAttributesCount == 0 then mempty else archVarint 16 (fromIntegral msg.resourceDroppedAttributesCount))
    <> V.foldl' (\acc v -> let sz = messageSize v in acc <> archSubmessage 26 sz (buildMessage v)) mempty msg.resourceEntityRefs
    <> encodeUnknownFields msg.resourceUnknownFields

instance MessageSize Resource where
  messageSize msg =
    (V.foldl' (\acc v -> acc + archSubmessageSize (messageSize v)) 0 msg.resourceAttributes)
    + (if msg.resourceDroppedAttributesCount == 0 then 0 else archVarintSize (fromIntegral msg.resourceDroppedAttributesCount))
    + (V.foldl' (\acc v -> acc + archSubmessageSize (messageSize v)) 0 msg.resourceEntityRefs)
    + unknownFieldsSize msg.resourceUnknownFields

instance MessageDecode Resource where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop V.empty 0 V.empty []
    where
      loop acc_0 acc_1 acc_2 acc_unknown_ = withTagM
        (pure (Resource {resourceAttributes = acc_0, resourceDroppedAttributesCount = acc_1, resourceEntityRefs = acc_2, resourceUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldMessage
            loop (acc_0 <> V.singleton v) acc_1 acc_2 acc_unknown_
          2 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop acc_0 v acc_2 acc_unknown_
          3 -> do
            v <- decodeFieldMessage
            loop acc_0 acc_1 (acc_2 <> V.singleton v) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 acc_1 acc_2 (uf : acc_unknown_))

instance ProtoMessage Resource where
  protoMessageName _ = "opentelemetry.proto.resource.v1.Resource"
  protoPackageName _ = "opentelemetry.proto.resource.v1"
  protoDefaultValue = defaultResource
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "attributes"
        , fdNumber = 1
        , fdTypeDesc = MessageType "opentelemetry.proto.common.v1.KeyValue"
        , fdLabel = LabelRepeated
        , fdGet = resourceAttributes
        , fdSet = \v m -> m { resourceAttributes = v }
        }), (2, SomeField FieldDescriptor
        { fdName = "dropped_attributes_count"
        , fdNumber = 2
        , fdTypeDesc = ScalarType UInt32Field
        , fdLabel = LabelOptional
        , fdGet = resourceDroppedAttributesCount
        , fdSet = \v m -> m { resourceDroppedAttributesCount = v }
        })
    , (3, SomeField FieldDescriptor
        { fdName = "entity_refs"
        , fdNumber = 3
        , fdTypeDesc = MessageType "opentelemetry.proto.common.v1.EntityRef"
        , fdLabel = LabelRepeated
        , fdGet = resourceEntityRefs
        , fdSet = \v m -> m { resourceEntityRefs = v }
        })
    ]

instance IsMessage Resource

instance Aeson.ToJSON Resource where
  toJSON msg = jsonObject
      [ "attributes" .=: msg.resourceAttributes
      , "droppedAttributesCount" .=: msg.resourceDroppedAttributesCount
      , "entityRefs" .=: msg.resourceEntityRefs
      ]

instance Aeson.FromJSON Resource where
  parseJSON = Aeson.withObject "Resource" $ \obj -> do
    fld_resourceAttributes <- parseFieldMaybe obj "attributes"
    fld_resourceDroppedAttributesCount <- parseFieldMaybe obj "droppedAttributesCount"
    fld_resourceEntityRefs <- parseFieldMaybe obj "entityRefs"
    pure defaultResource
      { resourceAttributes = maybe (resourceAttributes defaultResource) id fld_resourceAttributes
      , resourceDroppedAttributesCount = maybe (resourceDroppedAttributesCount defaultResource) id fld_resourceDroppedAttributesCount
      , resourceEntityRefs = maybe (resourceEntityRefs defaultResource) id fld_resourceEntityRefs
      , resourceUnknownFields = []
      }

instance Hashable Resource where
  hashWithSalt salt msg = V.foldl' hashWithSalt (hashWithSalt (V.foldl' hashWithSalt (salt) msg.resourceAttributes) msg.resourceDroppedAttributesCount) msg.resourceEntityRefs

instance Proto.Extension.HasExtensions Resource where
  messageUnknownFields = resourceUnknownFields
  setMessageUnknownFields !ufs msg = msg { resourceUnknownFields = ufs }

instance Semigroup Resource where
  a <> b = Resource
    { resourceAttributes = a.resourceAttributes <> b.resourceAttributes
    , resourceDroppedAttributesCount = if b.resourceDroppedAttributesCount == 0 then a.resourceDroppedAttributesCount else b.resourceDroppedAttributesCount
    , resourceEntityRefs = a.resourceEntityRefs <> b.resourceEntityRefs
    , resourceUnknownFields = a.resourceUnknownFields <> b.resourceUnknownFields
    }

instance Monoid Resource where
  mempty = defaultResource